package com.model.executive.dto;
// Generated Jun 18, 2013 3:22:25 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExecutiveDetails generated by hbm2java
 */
@Entity
@Table(name="executive_details")
public class ExecutiveDetails  implements java.io.Serializable {


     private Integer eid;
     private String name;
     private String contactnumber;
     private String joiningdate;
     private String email;
     private String address;
     private String remarks;

    public ExecutiveDetails() {
    }

    public ExecutiveDetails(String name, String contactnumber, String joiningdate, String email, String address, String remarks) {
       this.name = name;
       this.contactnumber = contactnumber;
       this.joiningdate = joiningdate;
       this.email = email;
       this.address = address;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="eid", unique=true, nullable=false)
    public Integer getEid() {
        return this.eid;
    }
    
    public void setEid(Integer eid) {
        this.eid = eid;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="contactnumber", length=45)
    public String getContactnumber() {
        return this.contactnumber;
    }
    
    public void setContactnumber(String contactnumber) {
        this.contactnumber = contactnumber;
    }
    
    @Column(name="joiningdate", length=45)
    public String getJoiningdate() {
        return this.joiningdate;
    }
    
    public void setJoiningdate(String joiningdate) {
        this.joiningdate = joiningdate;
    }
    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
     @Column(name="remarks", length=45)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


