package com.model.currentIssue.dto;
// Generated Oct 5, 2013 11:18:50 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CurrentIssue generated by hbm2java
 */
@Entity
@Table(name="current_issue")
public class CurrentIssue  implements java.io.Serializable {


     private Integer pci;
     private Integer currentissue;

    public CurrentIssue() {
    }

    public CurrentIssue(Integer currentissue) {
       this.currentissue = currentissue;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="pci", unique=true, nullable=false)
    public Integer getPci() {
        return this.pci;
    }
    
    public void setPci(Integer pci) {
        this.pci = pci;
    }
    
    @Column(name="currentissue")
    public Integer getCurrentissue() {
        return this.currentissue;
    }
    
    public void setCurrentissue(Integer currentissue) {
        this.currentissue = currentissue;
    }




}


