package com.model.personal.dto;
// Generated Jun 18, 2013 3:22:04 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;

/**
 * PersonalDetails generated by hbm2java
 */
@Entity
@Table(name="personal_details")

@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class PersonalDetails  implements java.io.Serializable {


     private Integer pid;
     private String name;
     private String contactnumber;
     private String cocontactnumber;
     private String addressline1;
     private String addressline2;
     private String city;
     private String dist;
     private String state;
     private String pincode;
     private String landmark;
     private String email;
     private String createddate;
     private String subscriptionfor;
     private String noofissues;
     private String subscriber;
     private String marketing;
     private String advertiser;
     private String complimentarysubscriber;
     private String subscribedby;
     private String remarks;
     private Integer archive;
     private Integer fromissueno;
     private Integer toissueno;
     private Integer totalissues;
     private String creditsubscribers;
     

    public PersonalDetails() {
    }

    public PersonalDetails(String name, String contactnumber, String cocontactnumber, String addressline1, String addressline2, String city, String dist, String state, String pincode, String landmark, String email, String createddate, String subscriptionfor, String noofissues, String subscriber, String marketing, String advertiser, String complimentarysubscriber, String subscribedby, String remarks, Integer archive, Integer fromissueno, Integer toissueno, Integer totalissues, String creditsubscribers) {
       this.name = name;
       this.contactnumber = contactnumber;
       this.cocontactnumber = cocontactnumber;
       this.addressline1 = addressline1;
       this.addressline2 = addressline2;
       this.city = city;
       this.dist = dist;
       this.state = state;
       this.pincode = pincode;
       this.landmark = landmark;
       this.email = email;
       this.createddate = createddate;
       this.subscriptionfor = subscriptionfor;
       this.noofissues = noofissues;
       this.subscriber = subscriber;
       this.marketing = marketing;
       this.advertiser = advertiser;
       this.complimentarysubscriber = complimentarysubscriber;
       this.subscribedby = subscribedby;
       this.remarks = remarks;
       this.archive = archive;
       this.fromissueno = fromissueno;
       this.toissueno = toissueno;
       this.totalissues = totalissues;
       this.creditsubscribers = creditsubscribers;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="pid", unique=true, nullable=false)
     
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="contactnumber", length=45)
    public String getContactnumber() {
        return this.contactnumber;
    }
    
    public void setContactnumber(String contactnumber) {
        this.contactnumber = contactnumber;
    }
    
    @Column(name="cocontactnumber", length=45)
    public String getCocontactnumber() {
        return this.cocontactnumber;
    }
    
    public void setCocontactnumber(String cocontactnumber) {
        this.cocontactnumber = cocontactnumber;
    }
    
    @Column(name="addressline1", length=5000)
    public String getAddressline1() {
        return this.addressline1;
    }
    
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }
    
    @Column(name="addressline2", length=100)
    public String getAddressline2() {
        return this.addressline2;
    }
    
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }
    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="dist", length=45)
    public String getDist() {
        return this.dist;
    }
    
    public void setDist(String dist) {
        this.dist = dist;
    }
    
    @Column(name="state", length=45)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="pincode", length=45)
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    
    @Column(name="landmark", length=100)
    public String getLandmark() {
        return this.landmark;
    }
    
    public void setLandmark(String landmark) {
        this.landmark = landmark;
    }
    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
   
    @Column(name="createddate", length=10)
    public String getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(String createddate) {
        this.createddate = createddate;
    }
    
    @Column(name="subscriptionfor", length=45)
    public String getSubscriptionfor() {
        return this.subscriptionfor;
    }
    
    public void setSubscriptionfor(String subscriptionfor) {
        this.subscriptionfor = subscriptionfor;
    }
    
    @Column(name="noofissues", length=45)
    public String getNoofissues() {
        return this.noofissues;
    }
    
    public void setNoofissues(String noofissues) {
        this.noofissues = noofissues;
    }
    
    @Column(name="subscriber", length=45)
    public String getSubscriber() {
        return this.subscriber;
    }
    
    public void setSubscriber(String subscriber) {
        this.subscriber = subscriber;
    }
    
    @Column(name="marketing", length=45)
    public String getMarketing() {
        return this.marketing;
    }
    
    public void setMarketing(String marketing) {
        this.marketing = marketing;
    }
    
    @Column(name="advertiser", length=45)
    public String getAdvertiser() {
        return this.advertiser;
    }
    
    public void setAdvertiser(String advertiser) {
        this.advertiser = advertiser;
    }
    
    @Column(name="complimentarysubscriber", length=45)
    public String getComplimentarysubscriber() {
        return this.complimentarysubscriber;
    }
    
    public void setComplimentarysubscriber(String complimentarysubscriber) {
        this.complimentarysubscriber = complimentarysubscriber;
    }
    
    @Column(name="subscribedby", length=45)
    public String getSubscribedby() {
        return this.subscribedby;
    }
    
    public void setSubscribedby(String subscribedby) {
        this.subscribedby = subscribedby;
    }
    
    @Column(name="remarks", length=500)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
     @Column(name="archive")
     
    public Integer getarchive() {
        return this.archive;
    }
    
    public void setarchive(Integer archive) {
        this.archive = archive;
    }

    @Column(name="fromissueno")
    public Integer getFromissueno() {
        return this.fromissueno;
    }
    
    public void setFromissueno(Integer fromissueno) {
        this.fromissueno = fromissueno;
    }
    
    
     @Column(name="toissueno")
    public Integer getToissueno() {
        return this.toissueno;
    }
    
    public void setToissueno(Integer toissueno) {
        this.toissueno = toissueno;
    }
    
     @Column(name="totalissues")
    public Integer getTotalissues() {
        return this.totalissues;
    }
    
    public void setTotalissues(Integer totalissues) {
        this.totalissues = totalissues;
    }

    /**
     * @return the creditsubscribers
     */
    @Column(name="creditsubscribers", length=45)
    public String getCreditsubscribers() {
        return creditsubscribers;
    }

    /**
     * @param creditsubscribers the creditsubscribers to set
     */
    public void setCreditsubscribers(String creditsubscribers) {
        this.creditsubscribers = creditsubscribers;
    }



}


